### PR TITLE
refactor: Adjust TAF scripts for changes to MessageBus configuration

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@cherrycl , there is one more change needed, but wasn't sure how it should be implemented.
For Core Data the SubscribeEnabled was removed and replaced by the lack of `SubscribeTopic` specified in the new `MessageBus.Topics` map.

Code for handling it is here:
https://github.com/edgexfoundry/edgex-go/blob/main/internal/core/data/controller/messaging/subscriber.go#L43-L48

**Comment by cherrycl** [comment]
Integration-test test [CoreConfig001](https://github.com/edgexfoundry/edgex-taf/blob/94d9125ed6e4065e97de48bf74f8d6c7bad18b65/TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot#L17) should be removed, because the `SubscribeEnabled` was removed.

> @cherrycl , there is one more change needed, but wasn't sure how it should be implemented. For Core Data the SubscribeEnabled was removed and replaced by the lack of `SubscribeTopic` specified in the new `MessageBus.Topics` map.
> 
> Code for handling it is here: https://github.com/edgexfoundry/edgex-go/blob/main/internal/core/data/controller/messaging/subscriber.go#L43-L48

**Comment by lenny-intel** [comment]
> Integration-test test [CoreConfig001](https://github.com/edgexfoundry/edgex-taf/blob/94d9125ed6e4065e97de48bf74f8d6c7bad18b65/TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot#L17) should be removed, because the `SubscribeEnabled` was removed.

Removed and renumber remaining Core Config tests

**Comment by cherrycl** [comment]
The `MESSAGEQUEUE` also needs to be replaced.
https://github.com/edgexfoundry/edgex-taf/blob/94d9125ed6e4065e97de48bf74f8d6c7bad18b65/TAF/utils/scripts/docker/get-compose-file.sh#L67-L70

**Comment by lenny-intel** [comment]
> The `MESSAGEQUEUE` also needs to be replaced.

Done. Strange that didn't show up in the searched from MessageQueue

**Review by cherrycl — APPROVED** [review]
LGTM

**Pull request merged**
