### PR TITLE
refactor: Update the route names to the new service key based names

### LINKED ISSUE #436: [TAF] Update scripts for new API Gateway route names that use the service keys
All API Gateway route names have changed to use the service keys as the route names., e.g. `coredata` route changed to `core-data`

All reference to the old names must be updated

### PR DESCRIPTION
**Pull request by lenny-intel**
closes #436

Signed-off-by: lenny <leonard.goodell@intel.com>

### CODE REVIEW

**Comment by lenny-intel** [comment]
@cherrycl , @cloudxxx8  please merge related PR once this PR is merged. THX!
https://github.com/edgexfoundry/edgex-go/pull/3513

**Comment by cherrycl** [comment]
The device-virtual service also needs to be updated.
https://github.com/edgexfoundry/edgex-taf/blob/b66e38cd5b0631719bb71fb2d502c0d2c053777d/TAF/config/device-virtual/configuration.py#L9

**Comment by cherrycl** [comment]
> The device-virtual service also needs to be updated.
> https://github.com/edgexfoundry/edgex-taf/blob/b66e38cd5b0631719bb71fb2d502c0d2c053777d/TAF/config/device-virtual/configuration.py#L9

Will fix this on issue #438.

**Review by cherrycl — APPROVED** [review]
LGTM

**Pull request merged**
